[package]
name = "orb-sound"
version = "0.1.0"
edition = "2021"
authors = ["Max Byshnev <max.byshnev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
thiserror-impl = "1.0.30"
